import h5py
import numpy as np
import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import argparse

def load_data(h5_path):
    if not os.path.exists(h5_path):
        raise FileNotFoundError(f"File not found: {h5_path}")
    
    # Open file
    f = h5py.File(h5_path, 'r')
    return f

def get_reaction_data(f, formula=None, rxn_id=None):
    data = f['data']
    
    if formula is None:
        formula = list(data.keys())[0]
    
    if rxn_id is None:
        rxn_id = list(data[formula].keys())[0]
        
    print(f"Loading reaction: Formula={formula}, ID={rxn_id}")
    
    if formula not in data or rxn_id not in data[formula]:
        raise ValueError(f"Reaction {formula}/{rxn_id} not found in dataset")
        
    return data[formula][rxn_id], formula, rxn_id

def get_all_reactions(f):
    """Returns a list of all (formula, rxn_id) tuples in the dataset."""
    reactions = []
    data = f['data']
    for formula in data.keys():
        for rxn_id in data[formula].keys():
            reactions.append((formula, rxn_id))
    return reactions

def extract_trajectory(reaction_group):
    atomic_numbers = reaction_group['atomic_numbers'][:]
    positions = reaction_group['positions'][:] # Shape (n_frames, n_atoms, 3)
    energies = reaction_group['wB97x_6-31G(d).energy'][:]
    return atomic_numbers, positions, energies

def get_symbol(z):
    pt = {
        1: 'H', 2: 'He', 
        3: 'Li', 4: 'Be', 5: 'B', 6: 'C', 7: 'N', 8: 'O', 9: 'F', 10: 'Ne',
        11: 'Na', 12: 'Mg', 13: 'Al', 14: 'Si', 15: 'P', 16: 'S', 17: 'Cl', 18: 'Ar',
        19: 'K', 20: 'Ca', 35: 'Br', 53: 'I'
    }
    return pt.get(z, 'X')

def save_xyz(filename, atomic_numbers, positions, energy=None):
    with open(filename, 'w') as f:
        f.write(f"{len(atomic_numbers)}\n")
        comment = "Generated by extract_and_visualize.py"
        if energy is not None:
            comment += f", Energy={energy:.6f}"
        f.write(f"{comment}\n")
        for z, pos in zip(atomic_numbers, positions):
            symbol = get_symbol(z)
            f.write(f"{symbol} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n")

def visualize_trajectory(atomic_numbers, positions, energies, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    n_frames = positions.shape[0]
    
    # Plot energy profile
    plt.figure(figsize=(10, 6))
    plt.plot(range(n_frames), energies, 'o-', label='Original Data')
    plt.xlabel('Frame Index')
    plt.ylabel('Energy (Hartree)')
    plt.title('Energy Profile along Trajectory')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(output_dir, "energy_profile.png"))
    plt.close()

    # Save XYZs and plots for each frame
    for i in range(n_frames):
        pos = positions[i]
        energy = energies[i]
        
        # Save XYZ
        xyz_file = os.path.join(output_dir, f"frame_{i:03d}.xyz")
        save_xyz(xyz_file, atomic_numbers, pos, energy)
        
        # Plot 3D structure
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        
        # Simple color mapping based on atomic number
        colors = []
        sizes = []
        for z in atomic_numbers:
            if z == 1: # H
                colors.append('white')
                sizes.append(50)
            elif z == 6: # C
                colors.append('grey')
                sizes.append(100)
            elif z == 7: # N
                colors.append('blue')
                sizes.append(100)
            elif z == 8: # O
                colors.append('red')
                sizes.append(100)
            else:
                colors.append('yellow')
                sizes.append(100)
                
        ax.scatter(pos[:, 0], pos[:, 1], pos[:, 2], c=colors, s=sizes, edgecolor='k')
        
        # Set limits to be consistent across frames if possible, or just let auto-scale
        # For better visualization, centering is good
        center = np.mean(pos, axis=0)
        ax.set_xlim(center[0]-3, center[0]+3)
        ax.set_ylim(center[1]-3, center[1]+3)
        ax.set_zlim(center[2]-3, center[2]+3)
        
        ax.set_title(f"Frame {i}, E={energy:.4f}")
        plt.savefig(os.path.join(output_dir, f"frame_{i:03d}.png"))
        plt.close(fig)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract and visualize transition state trajectory")
    parser.add_argument("--h5_path", type=str, default="Transition-State-Generation-Flow/dataset/transition1x/data/transition1x.h5", help="Path to h5 file")
    parser.add_argument("--output_dir", type=str, default="extracted_data", help="Output directory")
    parser.add_argument("--formula", type=str, default="C2H2N2O", help="Chemical formula to select")
    parser.add_argument("--rxn_id", type=str, default="rxn2091", help="Reaction ID to select")
    
    args = parser.parse_args()
    
    try:
        f = load_data(args.h5_path)
        grp, formula, rxn_id = get_reaction_data(f, args.formula, args.rxn_id)
        
        z, pos, energies = extract_trajectory(grp)
        print(f"Extracted {formula} reaction {rxn_id}")
        print(f"Trajectory length: {pos.shape[0]} frames")
        
        visualize_trajectory(z, pos, energies, args.output_dir)
        print(f"Data and visualizations saved to {args.output_dir}")
        
    except Exception as e:
        print(f"Error: {e}")
